# *$NUMPY$*

In [2]:
import numpy as np

### Array Creation

In [3]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
m1 = np.asmatrix('1,2,3; 4,5,6')
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [27]:
a2 = np.array(m1)
a2

array([[1, 2, 3],
       [4, 5, 6]])

**array vs matrix**: matrix - always 2D, matrix mult for "**", limited flexibiltiy, not default in ml. array - N-dimensional, element wise mult for "*"

In [62]:
np.arange(-4,4,1) #step wise 

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [63]:
np.linspace(-4,4,12) #No. of samples wise

array([-4.        , -3.27272727, -2.54545455, -1.81818182, -1.09090909,
       -0.36363636,  0.36363636,  1.09090909,  1.81818182,  2.54545455,
        3.27272727,  4.        ])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones((2,2), int)

array([[1, 1],
       [1, 1]])

In [29]:
np.empty((2,3))

array([[-8.34269278e-312,  8.34269277e-312,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [36]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Shape & Reshaping

In [38]:
a2.shape

(2, 3)

In [55]:
a3 = a2.reshape(3,2)
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
a3.ravel("C") #C - rowwise

array([1, 2, 3, 4, 5, 6])

In [59]:
a3.flatten("F") #Fortran - column wise

array([1, 3, 5, 2, 4, 6])

In [69]:
a4 = a3.T #Transpose
a4

array([[1, 3, 5],
       [2, 4, 6]])

In [73]:
a5 = np.expand_dims(a4,1)
a5

array([[[1, 3, 5]],

       [[2, 4, 6]]])

In [80]:
a5.shape #depth-blocks,row,column

(2, 1, 3)

In [81]:
a4.shape #row,column

(2, 3)

In [89]:
a5.squeeze() #remove dim(axes) of size = 1

array([[1, 3, 5],
       [2, 4, 6]])

### Indexing & Filtering

In [18]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
mask = a1>3
mask

array([[False, False, False],
       [ True,  True,  True]])

In [8]:
a1[mask]

array([4, 5, 6])

In [15]:
np.where(a1>3,"H","L") #If 

array([['L', 'L', 'L'],
       ['H', 'H', 'H']], dtype='<U1')

In [19]:
np.take(a1, [[0, 1], [2, 3]])  #indices to values

array([[1, 2],
       [3, 4]])

In [39]:
condlist = [a1<3, a1>3]
choicelist = [a1, a1**2]
a6 = np.select(condlist, choicelist, 55) #55 is default value

### Mathematical Operations

In [40]:
a1,a2,a6

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2, 55],
        [16, 25, 36]]))

In [41]:
np.add(a1,a2)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
np.subtract(a6,a1)

array([[ 0,  0, 52],
       [12, 20, 30]])

In [44]:
np.multiply(a1,a2) #elementwise mult

array([[ 1,  4,  9],
       [16, 25, 36]])

In [47]:
np.multiply(m1,m1) #elementwise mult

matrix([[ 1,  4,  9],
        [16, 25, 36]])

In [54]:
m2 = np.matrix("3,2; 8,7; 9,8")
m1,m2, m1*m2 #dot product

(matrix([[1, 2, 3],
         [4, 5, 6]]),
 matrix([[3, 2],
         [8, 7],
         [9, 8]]),
 matrix([[ 46,  40],
         [106,  91]]))

In [61]:
a7 = np.array(m2)
a1 @ a7, np.dot(a1,a7) #dot product for array

(array([[ 46,  40],
        [106,  91]]),
 array([[ 46,  40],
        [106,  91]]))

In [64]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
a8 = np.linspace(-8,2,8)
np.power(2,a1), np.sqrt(a6), np.log(a1), np.exp(a1), a8,  np.abs(a8)

(array([[ 2,  4,  8],
        [16, 32, 64]]),
 array([[1.        , 1.41421356, 7.41619849],
        [4.        , 5.        , 6.        ]]),
 array([[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]]),
 array([[  2.71828183,   7.3890561 ,  20.08553692],
        [ 54.59815003, 148.4131591 , 403.42879349]]),
 array([-8.        , -6.57142857, -5.14285714, -3.71428571, -2.28571429,
        -0.85714286,  0.57142857,  2.        ]),
 array([8.        , 6.57142857, 5.14285714, 3.71428571, 2.28571429,
        0.85714286, 0.57142857, 2.        ]))

### Aggregations

In [86]:
a1, np.sum(a1, axis=1), np.mean(a1), np.median(a1), np.std(a1).round(2), np.floor(np.var(a1)), np.min(a1), np.max(a1)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([ 6, 15]),
 np.float64(3.5),
 np.float64(3.5),
 np.float64(1.71),
 np.float64(2.0),
 np.int64(1),
 np.int64(6))

In [89]:
np.argmin(a1), np.argmax(a1) #return index

(np.int64(0), np.int64(5))

### Statistical

In [99]:
np.percentile(np.array([1,2,3,4,5]), np.array([1,10,50,80,100])) #uses interpolation: position = (p / 100) * (n - 1)

array([1.04, 1.4 , 3.  , 4.2 , 5.  ])

In [104]:
np.quantile(np.array([1,2,3,4,5]), np.array([0.25,0.5,1]))

array([2., 3., 5.])

In [111]:
a6, np.corrcoef(a6), np.cov(a6)

(array([[ 1,  2, 55],
        [16, 25, 36]]),
 array([[1.        , 0.90055938],
        [0.90055938, 1.        ]]),
 array([[954.33333333, 278.66666667],
        [278.66666667, 100.33333333]]))

**cov** = [ var(x)    cov(x,y) ]
[ cov(y,x)  var(y)   ]

exploded var due to outlier "55"

### Sorting & Ranking

In [150]:
np.sort(a6), np.argsort(a6)

(array([[ 1,  2, 55],
        [16, 25, 36]]),
 array([[0, 1, 2],
        [0, 1, 2]]))

In [151]:
a9 = np.array([[10, 64, 9, 2, 8], [34, 7, 4, 6, 5]])
np.partition(a9,kth=2)

array([[ 2,  8,  9, 10, 64],
       [ 4,  5,  6,  7, 34]])

### Linear Algebra

In [156]:
a10 = np.array([[2,4],[6,8]])
np.linalg.inv(a10) #matrix inverse

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

<img src="https://cdn1.byjus.com/wp-content/uploads/2018/04/inverse-matrix-3.jpg" width="350">

In [164]:
np.linalg.det(a10) #Determinant 

np.float64(-8.000000000000002)

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*-ycNEMicMOIR8WvzcBzERA@2x.jpeg" width="300">

In [166]:
a11 = np.array([[1,2],[3,-4]])
np.linalg.eig(a11) #Eigenvalues & Eigenvectors

EigResult(eigenvalues=array([ 2., -5.]), eigenvectors=array([[ 0.89442719, -0.31622777],
       [ 0.4472136 ,  0.9486833 ]]))

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*TdPrjB0rpALnR210BWqcjQ@2x.jpeg" width="300">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*hpU_jUvB9SInaO9H5xj_Eg@2x.jpeg" width="300">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Uc3F6OYQz-3wA0smlyI_tw@2x.jpeg" width="200">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ToE0nyoHVEwdxiuOwdP1jA@2x.jpeg" width="250">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*HQzJTGwJK9_O_skayURhoA@2x.jpeg" width="200">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sPkz01t9Wm6n4yXFkn_-eA@2x.jpeg" width="200">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ku7iQYLfC57kwgII2DtKSg@2x.jpeg" width="200">
<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*FUYhgRTROmpyPsYC0zyNdg@2x.jpeg" width="200">

In [171]:
a12 = np.array([[-4,-7],[1,4]])
np.linalg.svd(a12) #Singular Value Decomposition

SVDResult(U=array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]), S=array([9., 1.]), Vh=array([[ 0.4472136 ,  0.89442719],
       [-0.89442719,  0.4472136 ]]))

gn,
\begin{array}{l}A = \begin{bmatrix} -4 & -7\\ 1 & 4 \end{bmatrix}\end{array}
so,
\begin{array}{l}A^T = \begin{bmatrix} -4 & 1\\ -7 & 4 \end{bmatrix}\end{array}
\begin{array}{l}AA^T = \begin{bmatrix} -4 & -7\\ 1 & 4 \end{bmatrix}\begin{bmatrix} -4 & 1\\ -7 & 4 \end{bmatrix}=\begin{bmatrix} 65 & -32\\ -32 & 17 \end{bmatrix}\end{array}
Finding the eigenvector for AAT:<br>
<img src="https://cdn1.byjus.com/wp-content/uploads/2021/12/singular-value-decomposition-ex1.png" width="300">
<br>The eigenvalues of the matrix A⋅A′ are given by λ = 1, 81.
Now,
Eigenvectors for λ = 81 are:
\begin{array}{l}v_1 = \begin{bmatrix} -2 \\ 1 \end{bmatrix}\end{array}
Eigenvectors for λ = 1 are:
\begin{array}{l}v_2 = \begin{bmatrix} 0.5 \\ 1 \end{bmatrix}\end{array} <br>

<img src ="https://cdn1.byjus.com/wp-content/uploads/2021/12/singular-value-decomposition-ex2.png" width="400">
Similarly, we can find the eigenvectors for A’A as:
Eigenvectors for λ = 81 are
\begin{array}{l}v_1 = \begin{bmatrix} 0.5 \\ 1 \end{bmatrix}\end{array}
Eigenvectors for λ = 1 are:
\begin{array}{l}v_2 = \begin{bmatrix} -2 \\ 1 \end{bmatrix}\end{array}<br>
<img src = "https://cdn1.byjus.com/wp-content/uploads/2021/12/singular-value-decomposition-ex3.png" width="300">
Using these values, we can write the solution.<br>
<img src ="https://cdn1.byjus.com/wp-content/uploads/2021/12/singular-value-decomposition-ex4.png" width="300">
<img src ="https://cdn1.byjus.com/wp-content/uploads/2021/12/singular-value-decomposition-ex5.png" width="300">


In [172]:
np.linalg.norm([3,4]) #distance from origin (0,0,0) / size / length / magnitude of a vector

np.float64(5.0)